### ISSUE TITLE
Day flag is ignored

### ISSUE THREAD

**Issue by brendan-pike** [CarlFK/veyepar#9]
Probably across all script although I initially noted this effect while using tsdv.py, 
<code>./tsdv.py --client acqa --show february_2010_network_meeting -d 2010-02-05</code>
resulted in:
<code>File ".\/tsdv.py", line 35, in one_dv
    st = os.stat(pathname)</code>
<code>OSError: [Errno 2] No such file or directory: '/mnt/DBI/Clients/ACQA/Videos/dv/acqa/february_2010_network_meeting/dv/arkaba/2009-12-04/10:54:41.dv'</code>
The correct path should of been:
<code>/mnt/DBI/Clients/ACQA/Videos/dv/acqa/february_2010_network_meeting/dv/arkaba/2010-02-05/</code>

It appears to have used the day and dv file from the first episode it hit rather than the day I specified as the recording '10:54:41.dv' exists in the 2009-12-04 directory and not 2010-02-05.

**Comment by CarlFK** [comment]
tsdv figures out what datetime a video was recorded. 
until that has happened, nothing can filter on the date.
